supi: 'imsi-999700000000004'  # Update the SUPI for the second UE

mcc: '999'
mnc: '70'

protectionScheme: 0
homeNetworkPublicKey: '5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650'
homeNetworkPublicKeyId: 1

routingIndicator: '0000'

key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
op: 'E8ED289DEBA952E4283B54E88E6183CA'
opType: 'OPC'
amf: '8000'

imei: '356938035643804'
imeiSv: '4370816125816152'

tunNetmask: '255.255.255.0'

gnbSearchList:
  - 192.168.40.102

uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

sessions:
  - type: 'IPv4'
    apn: 'video'
    slice:
      sst: 2   # Second UE with slice sst: 2 and sd: 000002
      sd: "000002"

configured-nssai:
  - sst: 2
    sd: "000002"  # Configured for second UE

integrity:
  IA1: true
  IA2: true
  IA3: true

ciphering:
  EA1: true
  EA2: true
  EA3: true

integrityMaxRate:
  uplink: 'full'
  downlink: 'full'

